#!/usr/bin/env bash
# oracle.sh - `db` adapter for Oracle. Reference implementation.
#
# Verbs:  schema | erd | query
# Reads:  ORACLE_USER ORACLE_PASSWORD ORACLE_DSN [ORACLE_SCHEMAS]
# Also:   AREA_NAME, AREA_SCHEMA_OWNERS   (from the dispatcher)
# Contract: docs/adapters.md
#
# READ-ONLY. Point ORACLE_USER at a read-only role. It issues no DDL or DML.
#
# ---------------------------------------------------------------------------
# BEFORE YOU TRUST THIS
# Written against Oracle 11g+ with sqlplus on PATH, but NOT validated against a
# live instance by whoever shipped this template. Run `schema` once and read the
# output before relying on it. DBMS_METADATA privileges and 11g vs 19c
# behaviour differ between shops, and that is exactly the sort of thing that is
# wrong in a way you only notice three weeks later.
# ---------------------------------------------------------------------------
#
# TIMEOUTS. Oracle has no per-session statement timeout equivalent to
# Postgres's statement_timeout. Two things guard against a runaway query here:
#   1. this script wraps sqlplus in `timeout` when coreutils is available
#   2. you should ALSO cap CPU_PER_CALL on the read-only role's profile
# Rely on (2). (1) kills the client, not the server-side query.

set -uo pipefail

verb="${1:-}"
shift || true

OUT=""; SQL=""; PARAMS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --out)    OUT="${2:-}";       shift 2 ;;
    --sql)    SQL="${2:-}";       shift 2 ;;
    --param)  PARAMS+=("${2:-}"); shift 2 ;;
    --area) shift 2 ;;
    *)        shift ;;
  esac
done

cfg_error() { echo "  [oracle] $1" >&2; exit 4; }
up_error()  { echo "  [oracle] $1" >&2; exit 5; }

# Verb support is knowable without credentials, so it is checked FIRST.
# "this verb does not exist here" (3) and "you have not configured me" (4) send
# the caller in completely different directions.
case "$verb" in
  schema|erd|query) ;;
  *) echo "  [oracle] unknown verb '${verb:-}' (want: schema | erd | query)" >&2
     exit 3 ;;
esac

command -v sqlplus >/dev/null 2>&1 || cfg_error "sqlplus is not on PATH"
[ -n "${ORACLE_USER:-}" ]     || cfg_error "ORACLE_USER is not set - see .env.example"
[ -n "${ORACLE_PASSWORD:-}" ] || cfg_error "ORACLE_PASSWORD is not set - see .env.example"
[ -n "${ORACLE_DSN:-}" ]      || cfg_error "ORACLE_DSN is not set - see .env.example"

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Quote and upper-case the owner list, stripping anything that could close a
# string literal. Never interpolate raw input into SQL.
owners_in_list() {
  local raw="${AREA_SCHEMA_OWNERS:-${ORACLE_SCHEMAS:-}}"
  [ -n "$raw" ] || { printf 'USER'; return; }
  local out="" s
  IFS=',' read -ra _parts <<< "$raw"
  for s in "${_parts[@]}"; do
    s="$(printf '%s' "$s" | tr -d "[:space:]'\"" | tr '[:lower:]' '[:upper:]')"
    [ -n "$s" ] || continue
    out="${out:+$out,}'$s'"
  done
  printf '%s' "${out:-USER}"
}
OWNERS_SQL="$(owners_in_list)"
OWNERS_LABEL="${AREA_SCHEMA_OWNERS:-${ORACLE_SCHEMAS:-current user}}"

# Credentials go in on STDIN via CONNECT, never on the command line, so they
# never appear in the process table.
run_sql() {
  local settings="$1" body="$2" out rc
  local runner=(sqlplus -S -L /nolog)
  if command -v timeout >/dev/null 2>&1; then
    runner=(timeout "${ORACLE_QUERY_TIMEOUT:-120}" "${runner[@]}")
  fi
  out="$(
    {
      printf 'WHENEVER SQLERROR EXIT SQL.SQLCODE\n'
      printf 'WHENEVER OSERROR EXIT 9\n'
      printf 'CONNECT %s/%s@%s\n' "$ORACLE_USER" "$ORACLE_PASSWORD" "$ORACLE_DSN"
      printf '%s\n' "$settings"
      printf '%s\n' "$body"
      printf 'EXIT\n'
    } | "${runner[@]}" 2>&1
  )"
  rc=$?
  # Redact anything that could echo the DSN or user back out.
  printf '%s' "$out" | sed -e "s|${ORACLE_PASSWORD}|********|g"
  return $rc
}

SET_SNAPSHOT="SET HEADING OFF FEEDBACK OFF VERIFY OFF ECHO OFF TERMOUT ON
SET PAGESIZE 0 LINESIZE 32767 LONG 2000000 LONGCHUNKSIZE 2000000 TRIMSPOOL ON"
SET_QUERY="SET HEADING ON FEEDBACK OFF VERIFY OFF ECHO OFF PAGESIZE 200 LINESIZE 200"

header() {
  local c="$1"
  printf '%s GENERATED by scripts/adapters/db/oracle.sh on %s\n' "$c" "$STAMP"
  printf '%s Source: %s (%s). Do not hand-edit.\n' \
    "$c" "${AREA_NAME:-?}" "$OWNERS_LABEL"
  printf '%s Re-run: python scripts/snapshot_db.py %s\n' "$c" "${AREA_NAME:-?}"
}

emit() { if [ -n "$OUT" ]; then cat > "$OUT"; else cat; fi; }

case "$verb" in

  schema)
    body="BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SQLTERMINATOR',TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'PRETTY',TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'SEGMENT_ATTRIBUTES',FALSE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'STORAGE',FALSE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM,'TABLESPACE',FALSE);
END;
/
SELECT DBMS_METADATA.GET_DDL('TABLE', table_name, owner)
FROM all_tables
WHERE owner IN ($OWNERS_SQL)
ORDER BY owner, table_name;"
    if ! rows="$(run_sql "$SET_SNAPSHOT" "$body")"; then
      up_error "schema extract failed: $(printf '%s' "$rows" | tail -n 2 | tr '\n' ' ')"
    fi
    { header '--'; echo; printf '%s\n' "$rows"; } | emit
    ;;

  erd)
    body="SELECT rc.table_name || '|' || c.table_name
FROM all_constraints c
JOIN all_constraints rc
  ON rc.constraint_name = c.r_constraint_name
 AND rc.owner = c.r_owner
WHERE c.constraint_type = 'R'
  AND c.owner IN ($OWNERS_SQL)
ORDER BY 1, 2;"
    if ! rows="$(run_sql "$SET_SNAPSHOT" "$body")"; then
      up_error "constraint query failed: $(printf '%s' "$rows" | tail -n 2 | tr '\n' ' ')"
    fi
    {
      header '%%'
      echo
      echo 'erDiagram'
      found=0
      while IFS='|' read -r parent child; do
        parent="$(printf '%s' "${parent:-}" | tr -d '[:space:]')"
        child="$(printf '%s' "${child:-}" | tr -d '[:space:]')"
        [ -n "$parent" ] && [ -n "$child" ] || continue
        printf '  %s ||--o{ %s : has\n' "$parent" "$child"
        found=1
      done <<< "$rows"
      [ "$found" -eq 1 ] || \
        echo '  %% no foreign keys found - relationships may be enforced in code or triggers'
    } | emit
    ;;

  query)
    [ -n "$SQL" ] || cfg_error "no --sql was provided"
    printf '%s' "$SQL" | grep -Eiq '^[[:space:]]*(select|with)\b' || {
      echo "  [oracle] refusing: only SELECT and WITH are permitted" >&2
      exit 1
    }
    defines=""
    if [ "${#PARAMS[@]}" -gt 0 ]; then
      for p in "${PARAMS[@]}"; do
        k="${p%%=*}"; v="${p#*=}"
        k="$(printf '%s' "$k" | tr -cd '[:alnum:]_')"
        v="$(printf '%s' "$v" | tr -d "'\"")"
        defines="${defines}DEFINE ${k}='${v}'"$'\n'
      done
    fi
    statement="$SQL"
    case "$statement" in *\;) ;; *) statement="$statement;" ;; esac
    if ! rows="$(run_sql "$SET_QUERY" "${defines}${statement}")"; then
      up_error "query failed: $(printf '%s' "$rows" | tail -n 2 | tr '\n' ' ')"
    fi
    printf '%s\n' "$rows" | emit
    ;;

  *)
    echo "  [oracle] unknown verb '${verb:-}' (want: schema | erd | query)" >&2
    exit 3
    ;;
esac
