#!/usr/bin/env bash
# postgres.sh - `db` adapter for PostgreSQL. Working reference implementation.
#
# Verbs:  schema | erd | query
# Reads:  PGHOST PGPORT PGDATABASE PGUSER PGPASSWORD  (standard libpq vars)
# Also:   AREA_NAME, AREA_SCHEMA_OWNERS           (from the dispatcher)
# Contract: docs/adapters.md
#
# READ-ONLY. Point it at a read-only role. It never issues DDL or DML.

set -uo pipefail

verb="${1:-}"
shift || true

OUT=""; SQL=""; PARAMS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --out)    OUT="${2:-}";    shift 2 ;;
    --sql)    SQL="${2:-}";    shift 2 ;;
    --param)  PARAMS+=("${2:-}"); shift 2 ;;
    --area) shift 2 ;;
    *)        shift ;;
  esac
done

cfg_error() { echo "  [postgres] $1" >&2; exit 4; }
up_error()  { echo "  [postgres] $1" >&2; exit 5; }

# Verb support is knowable without credentials, so it is checked FIRST.
# "this verb does not exist here" (3) and "you have not configured me" (4) send
# the caller in completely different directions; getting the order wrong makes
# an unsupported verb look like a broken setup.
case "$verb" in
  schema|erd|query) ;;
  *) echo "  [postgres] unknown verb '${verb:-}' (want: schema | erd | query)" >&2
     exit 3 ;;
esac

command -v psql >/dev/null 2>&1 || cfg_error "psql is not on PATH"
[ -n "${PGDATABASE:-}" ] || cfg_error "PGDATABASE is not set - see .env.example"

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
OWNERS="${AREA_SCHEMA_OWNERS:-}"

# check.py fails any generated artifact that does not carry this.
header() {
  local c="$1"
  printf '%s GENERATED by scripts/adapters/db/postgres.sh on %s\n' "$c" "$STAMP"
  printf '%s Source: %s / %s (%s). Do not hand-edit.\n' \
    "$c" "${AREA_NAME:-?}" "$PGDATABASE" "${OWNERS:-all schemas}"
  printf '%s Re-run: python scripts/snapshot_db.py %s\n' "$c" "${AREA_NAME:-?}"
}

emit() { if [ -n "$OUT" ]; then cat > "$OUT"; else cat; fi; }

schema_filter_sql() {
  if [ -n "$OWNERS" ]; then
    printf "AND n.nspname = ANY(string_to_array('%s', ','))" "$OWNERS"
  else
    printf "AND n.nspname NOT IN ('pg_catalog','information_schema')"
  fi
}

case "$verb" in

  schema)
    command -v pg_dump >/dev/null 2>&1 || cfg_error "pg_dump is not on PATH"
    args=(--schema-only --no-owner --no-privileges)
    if [ -n "$OWNERS" ]; then
      IFS=',' read -ra _schemas <<< "$OWNERS"
      for s in "${_schemas[@]}"; do args+=(-n "$s"); done
    fi
    if ! body="$(pg_dump "${args[@]}" 2>&1)"; then
      up_error "pg_dump failed: $(printf '%s' "$body" | tail -n 1)"
    fi
    { header '--'; echo; printf '%s\n' "$body"; } | emit
    ;;

  erd)
    q="SELECT c.conrelid::regclass::text, c.confrelid::regclass::text
       FROM pg_constraint c
       JOIN pg_namespace n ON n.oid = c.connamespace
       WHERE c.contype = 'f' $(schema_filter_sql)
       ORDER BY 1, 2"
    if ! rows="$(psql -At -F '|' -v ON_ERROR_STOP=1 -c "$q" 2>&1)"; then
      up_error "query failed: $(printf '%s' "$rows" | tail -n 1)"
    fi
    {
      header '%%'
      echo
      echo 'erDiagram'
      if [ -z "$rows" ]; then
        echo '  %% no foreign keys found - relationships may be enforced in code'
      else
        while IFS='|' read -r child parent; do
          [ -n "${child:-}" ] || continue
          printf '  %s ||--o{ %s : has\n' "$parent" "$child"
        done <<< "$rows"
      fi
    } | emit
    ;;

  query)
    [ -n "$SQL" ] || cfg_error "no --sql was provided"
    printf '%s' "$SQL" | grep -Eiq '^[[:space:]]*(select|with)\b' || {
      echo "  [postgres] refusing: only SELECT and WITH are permitted" >&2
      exit 1
    }
    pv=()
    if [ "${#PARAMS[@]}" -gt 0 ]; then
      for p in "${PARAMS[@]}"; do pv+=(-v "$p"); done
    fi
    # A statement timeout on everything, without exception.
    if ! rows="$(psql -v ON_ERROR_STOP=1 "${pv[@]+"${pv[@]}"}" \
                   -c "SET statement_timeout = '${PG_STATEMENT_TIMEOUT:-10s}'" \
                   -c "$SQL" 2>&1)"; then
      up_error "query failed: $(printf '%s' "$rows" | tail -n 1)"
    fi
    printf '%s\n' "$rows" | emit
    ;;

  *)
    echo "  [postgres] unknown verb '${verb:-}' (want: schema | erd | query)" >&2
    exit 3
    ;;
esac
