"""Shared helpers for the control-plane scripts.

Control plane ONLY: git orchestration, YAML, paths, validation, reporting.
Nothing here knows how to build or run your project. Anything that has to touch
a live external system goes through an adapter - see docs/adapters.md.

The model is one collection: AREAS. An area is a named part of the work with a
card describing it. Its `kind` says where it physically lives:

    local      part of this repository, described by `paths:`   (the default)
    repo       an external repository, checked out into systems/
    database   logic that lives in a database, with no repo at all
    fileshare  anything else with no repo

A general project declares local areas. A legacy-modernization project declares
repo and database areas. Same model, same cards, same validation.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
ROOT = SCRIPTS_DIR.parent
PROJECT_FILE = ROOT / "project.yaml"
MAP_DIR = ROOT / "map"
PROFILES_DIR = ROOT / "profiles"

ADAPTER_FAMILIES = ("db", "capture", "test")
VALID_KINDS = ("local", "repo", "database", "fileshare")
VALID_ACCESS = ("read-only", "write")

# A ref that moves under you. A card describes a commit; if the ref drifts, the
# card silently becomes fiction.
MOVING_REFS = {"main", "master", "develop", "trunk", "default", "HEAD"}

# Credential-bearing file patterns. Mirrored into .rgignore so hardcoded
# secrets are not pulled into a transcript incidentally. Useful side effect: it
# also removes noisy config from every search result.
SECRET_FILE_PATTERNS = [
    "**/*.properties",
    "**/web.xml",
    "**/*.config",
    "**/application*.yml",
    "**/application*.yaml",
    "**/tnsnames.ora",
    "**/*.pem",
    "**/*.p12",
    "**/*.jks",
    "**/id_rsa*",
]

# An area card is one page. These are the sections that carry the weight; a
# profile may require more (the legacy profile adds "Seams").
REQUIRED_CARD_SECTIONS = ["Owns", "Interfaces", "Landmines", "Do not read"]
REQUIRED_CARD_FIELDS = ["Surveyed:", "Confidence:", "Stack:", "Health:"]
# Exactly one of these locates the area. Which one depends on its kind.
CARD_SOURCE_FIELDS = ["Path:", "Repo:", "Schema:", "Location:"]

GENERATED_HEADER = "GENERATED"
STATUS_MARKER = "<!-- BELOW THIS LINE IS GENERATED by scripts/status.py"

# Budgets, in estimated tokens.
TIER0_TOKEN_BUDGET = 1500       # AGENTS.md + CLAUDE.md, paid every turn
STATUS_TOKEN_BUDGET = 900       # STATUS.md; past this it is becoming a wiki
CARD_TOKEN_BUDGET = 2000        # an area card that costs more than this is not
                                # cheaper than reading the code
AGENTS_MD_MAX_LINES = 150


# ---------------------------------------------------------------------------
# output
# ---------------------------------------------------------------------------

_COLOR = sys.stderr.isatty() and not os.environ.get("NO_COLOR")

# Our own strings are ASCII by policy, but filenames and other external data are
# not. A cp1252 console raises UnicodeEncodeError rather than degrading, which
# would crash a reporting tool over a character in somebody's path.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(errors="replace")
    except (AttributeError, ValueError):  # not a reconfigurable stream
        pass


def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _COLOR else text


def info(msg: str) -> None:
    print(msg, file=sys.stderr)


def ok(msg: str) -> None:
    print(f"{_c('32', 'ok')}   {msg}", file=sys.stderr)


def warn(msg: str) -> None:
    print(f"{_c('33', 'warn')} {msg}", file=sys.stderr)


def err(msg: str) -> None:
    print(f"{_c('31', 'FAIL')} {msg}", file=sys.stderr)


def die(msg: str, code: int = 1):
    err(msg)
    raise SystemExit(code)


def estimate_tokens(text: str) -> int:
    """Rough token count. ~4 chars/token is close enough for budgeting."""
    return max(1, round(len(text) / 4))


# ---------------------------------------------------------------------------
# yaml
# ---------------------------------------------------------------------------


def load_yaml(path: Path):
    """-> (data, parser_name). Falls back to the bundled subset parser."""
    text = Path(path).read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore
    except ImportError:
        import _minyaml

        try:
            return _minyaml.parse(text) or {}, "minyaml"
        except _minyaml.MinYamlError as exc:
            die(
                f"{path.name}: {exc}\n"
                "     The bundled fallback parser handles only the documented "
                "subset.\n     Fix the file, or install PyYAML: pip install pyyaml"
            )
    return yaml.safe_load(text) or {}, "pyyaml"


# ---------------------------------------------------------------------------
# model
# ---------------------------------------------------------------------------


@dataclass
class Area:
    name: str
    kind: str = "local"
    survey: bool = False
    owner: str = ""
    access: str = "read-only"

    # local
    paths: list = field(default_factory=list)

    # repo
    url: "str | None" = None
    ref: "str | None" = None
    sparse: list = field(default_factory=list)
    derive: list = field(default_factory=list)

    # database
    schema_owners: list = field(default_factory=list)

    exclude_from_search: list = field(default_factory=list)
    stack: dict = field(default_factory=dict)
    adapters: dict = field(default_factory=dict)

    @property
    def checkout(self) -> Path:
        """Where a repo area lands on disk. Meaningless for other kinds."""
        return ROOT / "systems" / self.name

    @property
    def card_dir(self) -> Path:
        return MAP_DIR / self.name

    @property
    def card(self) -> Path:
        return self.card_dir / "CARD.md"

    @property
    def clonable(self) -> bool:
        return self.kind == "repo"

    @property
    def search_root(self) -> str:
        """Path prefix for this area's exclusions, relative to the repo root."""
        return f"systems/{self.name}/" if self.kind == "repo" else ""

    def owns_path(self, rel_path: str) -> bool:
        """Does `rel_path` (repo-relative, posix) belong to this area?"""
        from fnmatch import fnmatch

        rel_path = rel_path.replace("\\", "/").lstrip("./")
        if self.kind == "repo":
            return rel_path.startswith(f"systems/{self.name}/")
        for pattern in self.paths:
            pattern = str(pattern).replace("\\", "/")
            if fnmatch(rel_path, pattern) or rel_path.startswith(
                pattern.split("*", 1)[0].rstrip("/") + "/"
            ):
                return True
        return False


@dataclass
class Project:
    name: str
    profile: str
    areas: "list[Area]"
    commands: dict
    parser: str
    path: Path
    errors: "list[str]" = field(default_factory=list)

    def get(self, name: str) -> "Area | None":
        for a in self.areas:
            if a.name == name:
                return a
        return None

    def require(self, name: str) -> Area:
        found = self.get(name)
        if found is None:
            known = ", ".join(a.name for a in self.areas) or "(none declared)"
            die(f"unknown area {name!r}. Declared: {known}")
        return found  # type: ignore[return-value]

    def area_for(self, rel_path: str) -> "Area | None":
        for a in self.areas:
            if a.owns_path(rel_path):
                return a
        return None

    @property
    def repo_areas(self) -> "list[Area]":
        return [a for a in self.areas if a.kind == "repo"]


def _as_list(value) -> list:
    if value is None:
        return []
    return value if isinstance(value, list) else [value]


def load_project(path: Path = PROJECT_FILE) -> Project:
    """Load and normalize project.yaml.

    Schema problems are collected into `.errors` rather than raised, so check.py
    reports all of them in one pass instead of one per run.
    """
    if not path.exists():
        die(
            f"{path.name} not found. Are you in the project root?\n"
            "     If this is a new project: python scripts/init.py"
        )

    data, parser = load_yaml(path)
    errors: list[str] = []

    if not isinstance(data, dict):
        die(f"{path.name}: expected a mapping at the top level")

    defaults = data.get("defaults") or {}
    name = str(data.get("project") or "<unnamed>")
    profile = str(data.get("profile") or "general")
    commands = data.get("commands") or {}
    if not isinstance(commands, dict):
        errors.append("'commands' must be a mapping of name -> shell command")
        commands = {}

    if profile and not (PROFILES_DIR / profile).is_dir():
        errors.append(
            f"profile {profile!r} has no directory under profiles/. "
            f"Available: {', '.join(sorted(p.name for p in PROFILES_DIR.iterdir() if p.is_dir())) if PROFILES_DIR.is_dir() else 'none'}"
        )

    areas: list[Area] = []
    seen: set[str] = set()

    for idx, raw in enumerate(_as_list(data.get("areas"))):
        where = f"areas[{idx}]"
        if not isinstance(raw, dict):
            errors.append(f"{where}: expected a mapping")
            continue

        aname = raw.get("name")
        if not aname:
            errors.append(f"{where}: missing required field 'name'")
            continue
        aname = str(aname)
        if aname in seen:
            errors.append(f"{where}: duplicate area name {aname!r}")
            continue
        seen.add(aname)

        kind = str(raw.get("kind", "local"))
        if kind not in VALID_KINDS:
            errors.append(f"{aname}: kind {kind!r} not one of {VALID_KINDS}")

        access = str(raw.get("access", defaults.get("access", "read-only")))
        if access not in VALID_ACCESS:
            errors.append(f"{aname}: access {access!r} not one of {VALID_ACCESS}")

        paths = _as_list(raw.get("paths"))
        url, ref = raw.get("url"), raw.get("ref")

        if kind == "local":
            if not paths:
                errors.append(
                    f"{aname}: kind 'local' requires 'paths' - without it nothing "
                    "can tell which files belong to this area"
                )
            if url or ref:
                errors.append(f"{aname}: kind 'local' has no 'url'/'ref'")
        elif kind == "repo":
            if not url:
                errors.append(f"{aname}: kind 'repo' requires 'url'")
            if not ref:
                errors.append(
                    f"{aname}: kind 'repo' requires 'ref' - an unpinned area "
                    "cannot be surveyed reliably"
                )
        elif url or ref:
            errors.append(
                f"{aname}: kind {kind!r} has no repo, so 'url'/'ref' are meaningless"
            )

        adapters = raw.get("adapters") or {}
        if not isinstance(adapters, dict):
            errors.append(f"{aname}: 'adapters' must be a mapping")
            adapters = {}
        for fam in adapters:
            if fam not in ADAPTER_FAMILIES:
                errors.append(
                    f"{aname}: unknown adapter family {fam!r}; "
                    f"expected one of {ADAPTER_FAMILIES}"
                )

        for d_idx, d in enumerate(_as_list(raw.get("derive"))):
            if not isinstance(d, dict) or not {"tool", "from", "to"} <= set(d):
                errors.append(f"{aname}: derive[{d_idx}] needs 'tool', 'from' and 'to'")

        areas.append(
            Area(
                name=aname,
                kind=kind,
                survey=bool(raw.get("survey", defaults.get("survey", False))),
                owner=str(raw.get("owner") or ""),
                access=access,
                paths=paths,
                url=str(url) if url else None,
                ref=str(ref) if ref else None,
                sparse=_as_list(raw.get("sparse")),
                derive=_as_list(raw.get("derive")),
                schema_owners=_as_list(raw.get("schema_owners")),
                exclude_from_search=_as_list(raw.get("exclude_from_search")),
                stack=raw.get("stack") or {},
                adapters=adapters,
            )
        )

    return Project(
        name=name,
        profile=profile,
        areas=areas,
        commands=commands,
        parser=parser,
        path=path,
        errors=errors,
    )


# ---------------------------------------------------------------------------
# profiles
# ---------------------------------------------------------------------------


def profile_dir(project: Project) -> "Path | None":
    candidate = PROFILES_DIR / project.profile
    return candidate if candidate.is_dir() else None


def load_profile_rules(project: Project):
    """Import profiles/<profile>/rules.py, or None. Never raises."""
    directory = profile_dir(project)
    if directory is None:
        return None
    module_path = directory / "rules.py"
    if not module_path.is_file():
        return None
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        f"profile_{project.profile}_rules", module_path
    )
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# adapters
# ---------------------------------------------------------------------------


def resolve_adapter(area: Area, family: str):
    """-> (name, path).

    name is None  -> family not declared for this area (not applicable)
    path is None  -> declared but no such adapter on disk (an error)
    """
    name = (area.adapters or {}).get(family)
    if not name or str(name).lower() == "none":
        return None, None
    for base in adapter_search_paths(family):
        for ext in (".sh", ".py", ".ps1", ".cmd", ""):
            candidate = base / f"{name}{ext}"
            if candidate.is_file():
                return str(name), candidate
    return str(name), None


def adapter_search_paths(family: str) -> "list[Path]":
    """Core first, then every profile. Profiles ship their own adapters."""
    found = [SCRIPTS_DIR / "adapters" / family]
    if PROFILES_DIR.is_dir():
        for profile in sorted(PROFILES_DIR.iterdir()):
            candidate = profile / "adapters" / family
            if candidate.is_dir():
                found.append(candidate)
    return found


def adapter_command(path: Path) -> "list[str]":
    """Argv prefix for invoking an adapter, chosen by extension."""
    suffix = path.suffix.lower()
    if suffix == ".py":
        return [sys.executable, str(path)]
    if suffix == ".ps1":
        return ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass",
                "-File", str(path)]
    if suffix == ".sh":
        return ["bash", str(path)]
    return [str(path)]


def load_dotenv(path: "Path | None" = None) -> dict:
    """Read .env into a dict for the CHILD process environment.

    This is the only place .env is read. Values are never printed, logged, or
    returned on stdout - that is the entire reason credentials travel this way
    instead of on a command line where they would land in a transcript.
    """
    path = path or (ROOT / ".env")
    env: dict = {}
    if not path.exists():
        return env
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        env[key.strip()] = value
    return env


def adapter_env(area: Area) -> dict:
    """The variables every adapter receives. Documented in docs/adapters.md -
    an adapter never has to parse project.yaml."""
    return {
        "PROJECT_ROOT": str(ROOT),
        "AREA_NAME": area.name,
        "AREA_KIND": area.kind,
        "AREA_REF": area.ref or "",
        "AREA_CHECKOUT": str(area.checkout),
        "AREA_CARD_DIR": str(area.card_dir),
        "AREA_SCHEMA_OWNERS": ",".join(str(o) for o in area.schema_owners),
        "AREA_DATABASE": str((area.stack or {}).get("database", "")),
    }


def run_adapter(
    area: Area,
    family: str,
    verb: str,
    extra: "tuple | list" = (),
    out: "Path | None" = None,
) -> int:
    """Resolve and exec the adapter. Returns its exit code verbatim.

    Exit 3 ('not applicable') is a normal answer, not a failure: an area with no
    observable boundary genuinely has no 'record' verb.
    """
    name, path = resolve_adapter(area, family)
    if name is None:
        info(f"     {area.name}: no '{family}' adapter declared - nothing to do")
        return 3
    if path is None:
        err(f"{area.name}: adapter {name!r} for '{family}' not found")
        info("       Looked in: " + ", ".join(
            str(p.relative_to(ROOT)) for p in adapter_search_paths(family)))
        info("       See docs/adapters.md")
        return 1

    argv = adapter_command(path) + [verb, "--area", area.name]
    if out is not None:
        Path(out).parent.mkdir(parents=True, exist_ok=True)
        argv += ["--out", str(out)]
    argv += [str(a) for a in extra]

    child = {**os.environ, **load_dotenv(), **adapter_env(area)}
    code = subprocess.run(argv, cwd=str(ROOT), env=child).returncode

    if code == 0:
        ok(f"{area.name}: {family} {verb} -> {out or 'stdout'}")
    elif code == 3:
        info(f"     {area.name}: {family} {verb} not applicable ({name})")
    elif code == 4:
        err(f"{area.name}: {name} is missing credentials or configuration")
        info("       Fill the relevant entries in .env - see .env.example")
    elif code == 5:
        err(f"{area.name}: {name} could not reach the upstream system")
    else:
        err(f"{area.name}: {name} {verb} failed (exit {code})")
    return code


def adapter_status(code: int) -> int:
    """Collapse an adapter exit code into a process exit status.
    'Not applicable' is not a failure."""
    return 0 if code in (0, 3) else 1


# ---------------------------------------------------------------------------
# .rgignore
# ---------------------------------------------------------------------------


def rgignore_text(project: Project) -> str:
    """Render .rgignore from project.yaml. The single canonical generator -
    sync.py writes it, check.py compares against it."""
    lines = [
        f"# {GENERATED_HEADER} by scripts/sync.py from project.yaml.",
        "# Do not hand-edit. Re-run: python scripts/sync.py",
        "",
        "# --- always ---",
        ".git/",
        "systems/**/.git/",
        "__pycache__/",
        "",
        "# --- credential-bearing files ---",
        "# These also strip noisy config out of every search result.",
    ]
    lines += SECRET_FILE_PATTERNS
    for area in project.areas:
        if not area.exclude_from_search:
            continue
        lines += ["", f"# --- {area.name} ---"]
        for pattern in area.exclude_from_search:
            lines.append(f"{area.search_root}{str(pattern).lstrip('/')}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# git
# ---------------------------------------------------------------------------


def git(*args: str, cwd: "Path | None" = None, check: bool = False):
    return subprocess.run(
        ["git", *args],
        cwd=str(cwd or ROOT),
        capture_output=True,
        text=True,
        check=check,
    )


def is_git_repo(cwd: "Path | None" = None) -> bool:
    result = git("rev-parse", "--is-inside-work-tree", cwd=cwd)
    return result.returncode == 0 and result.stdout.strip() == "true"


def tracked_files() -> "list[str]":
    result = git("ls-files")
    return result.stdout.splitlines() if result.returncode == 0 else []


def has_commits() -> bool:
    """A freshly `git init`ed repo tracks nothing, which would make every
    'is X tracked?' check fire spuriously on day one."""
    return git("rev-parse", "--verify", "HEAD").returncode == 0


def is_pinned(ref: "str | None") -> bool:
    """A ref is pinned if it is a SHA or a tag-shaped name, not a branch."""
    if not ref:
        return False
    if ref in MOVING_REFS:
        return False
    if re.fullmatch(r"[0-9a-f]{7,40}", ref):
        return True
    return not ref.startswith(("refs/heads/", "heads/"))


def which(tool: str) -> "str | None":
    from shutil import which as _which

    return _which(tool)
